[workspace]
members = [
    "contracts/stream-vault",
    "contracts/milestone-escrow",
    "contracts/stream-factory",
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = { version = "22.0.0" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
panic = "abort"
lto = true
codegen-units = 1

